### ISSUE TITLE
glu does not compile on OSX 10.8.2

### ISSUE THREAD

**Issue by jimarnold** [go-gl-legacy/glu#16]
glu.h on my install of OSX does not define _GLUfuncptr - the nearest equivalent appears to be 'CallBackFunc'. go-gl/glu thus fails to compile (see below). I can fix this by patching callback.h to define _GLUfuncptr:

```
typedef GLvoid (*_GLUfuncptr)();
```

Do others have this issue on OSX?

<pre>
> go get github.com/go-gl/glu
# github.com/go-gl/glu
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c: In function ‘setGluTessCallback’:
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:9: error: ‘_GLUfuncptr’ undeclared (first use in this function)
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:9: error: (Each undeclared identifier is reported only once
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:9: error: for each function it appears in.)
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:9: error: expected ‘;’ before ‘func’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:12: error: ‘func’ undeclared (first use in this function)
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:12: error: expected ‘;’ before ‘goTessBeginData’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:15: error: expected ‘;’ before ‘goTessVertexData’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:18: error: expected ‘;’ before ‘goTessEndData’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:21: error: expected ‘;’ before ‘goTessErrorData’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:24: error: expected ‘;’ before ‘goTessEdgeFlagData’
/usr/local/Cellar/go/1.0.3/src/pkg/github.com/go-gl/glu/callback.c:27: error: expected ‘;’ before ‘goTessCombineData’
</pre>
